import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemePovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start justify-between`}>
        <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
        <Sidebar />
        <main className="grid w-full h-full">
          <Header />
          <div className="p-2">
            {children}
          </div>
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
